language: node_js
node_js:
- '6'
branches:
  only:
  - master
before_install:
- npm install -g bower
- npm install -g brunch
install:
- npm install
script:
- brunch build --production
after_success:
- cd "$TRAVIS_BUILD_DIR"
- cd public
- git init
- git config user.name "travis"
- git config user.email "travis"
- git add .
- git commit -m "Travis build nr. $TRAVIS_BUILD_NUMBER"
- git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:gh-pages
  > /dev/null
- echo 'deployed!'
env:
  global:
  - secure: D9ZU8ZhcPE93NUE3gT/nIUaIRU1qXOKHXfaiv8kvwSlenrwQrV4vEpvhvPUBrMkp9oCvAYl0StsvsMj17tLkzGzl9JKiyIUlrKt8+J7GqfLi7Jj75sPjHWmOtXUGs+CQv/OtIxEk9wWQo8Y9CL09n8+NjYfQKGdGWUTfE9S6lwk6amvxvSgSIQKsvz/r80w1YwlNrBS/uOm8Ivd0E4SV4G3c8bppJIbUtyTYzrHmGj98UNWyIUjDD5pnfEkcBn9rWny8foSPWrOQqZV8AOIqBuTcTuoGgIGZiH4lU2KOiAdnMhbb5w6hgEyKuMI7La5pwmN6yj6O/t+0LCKtpWd0GF6YVUlL2bpBWjd+XvP7VneQo42Fpe9542GS37r7eltN/FnlyakTu7FjOrkaKeU2djLpRx14inWUpPyxHIprbnQdMPHJVpimn2SKz7rcHjqkuW949pk8tXyO8isB+xwsrv/TM/17UFCLCt+QbNt4tpRsJrC4HSVRoclIAyhLe4hti4WNSA/WnL55xeI0yzkp3wc2Sb1/tFQw0yBlJLaFM93PS/8hmKnIlcUd3nPf/xxjXELViQMS2V4XMy4wKiNhr4+o4jpzJ1IhBo9od+a2W6GHanfWCuiYYIegLBb6htK8zbDU0ujai9Q/9PcmogYHkCxzkiYokPROnte4Qs6aTGo=
  - secure: kYAMj/MtiYDrb8mmMnaSfhMKKoEL+HGo7Roq0XIK7MpV3ouQ18fjG3Xai038V2DZFndmVtjIkdX+afQja11n17s1qUgJjcIsm5LDjsgUyMuOtRnw8bjh5c/lDFloc7PwZK5K2aTqJAR5lIgmGOqxvfUbOxLKcT2hw7S0Qvk+KM+jtIf+4fNDIYYItknYBKsb3W5hIfCFWGrK6QWMVo3kds3v7kNXT2y2i7eVKj73agTXxgce5lL9uS0LZ0IMS9DWq6Y58Sakb8je1XfOn1qFTRe8/M0hp/p2vORh+Fyr2nsaIPqEsoYeeFQwTZ6iAfi7ktHoIuv2AHOqlKNEle3OuYTKrKD0Ulbrpf/gvNrmxlfRSq1VGtHCkcEKAg8lsPHWC2T/Lriw77RG3N+CgwVZ8hO3dzPJAOvB3HqXm8+1a2kIwPQhLvwCx2maXHDmwckFzsFTRwTZ3u1mHK31rcGeOTvsatef4bmirtc2e5/1RjCdSVTNp73idW/7KQNpIirh9qguDDbwVOLuO5f2VhA2jamxUkO/AT8Ka1SY3wUt6zE980XoQS/YfKmtVT/KqoG26I6fRwyX4gD+pfaAAl8aP5nUvQHsrb0cPTe8tACGffWA6zeafVzntYs+a75kwZs38VIjTkhdXUs+5e9vuO+1oYoF6+zwyAMN7g9/75bCFz0=
