language: node_js
node_js:
- '6'
branches:
  only:
  - master
before_install:
- npm install -g bower
- npm install -g brunch
install:
- npm install
script:
- brunch build --production
after_success:
- cd "$TRAVIS_BUILD_DIR"
- cd public
- git init
- git config user.name "travis"
- git config user.email "travis"
- git add .
- git commit -m "Travis build nr. $TRAVIS_BUILD_NUMBER"
- git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:gh-pages > /dev/null
- echo 'deployed!'
env:
  global:
  - secure: D9ZU8ZhcPE93NUE3gT/nIUaIRU1qXOKHXfaiv8kvwSlenrwQrV4vEpvhvPUBrMkp9oCvAYl0StsvsMj17tLkzGzl9JKiyIUlrKt8+J7GqfLi7Jj75sPjHWmOtXUGs+CQv/OtIxEk9wWQo8Y9CL09n8+NjYfQKGdGWUTfE9S6lwk6amvxvSgSIQKsvz/r80w1YwlNrBS/uOm8Ivd0E4SV4G3c8bppJIbUtyTYzrHmGj98UNWyIUjDD5pnfEkcBn9rWny8foSPWrOQqZV8AOIqBuTcTuoGgIGZiH4lU2KOiAdnMhbb5w6hgEyKuMI7La5pwmN6yj6O/t+0LCKtpWd0GF6YVUlL2bpBWjd+XvP7VneQo42Fpe9542GS37r7eltN/FnlyakTu7FjOrkaKeU2djLpRx14inWUpPyxHIprbnQdMPHJVpimn2SKz7rcHjqkuW949pk8tXyO8isB+xwsrv/TM/17UFCLCt+QbNt4tpRsJrC4HSVRoclIAyhLe4hti4WNSA/WnL55xeI0yzkp3wc2Sb1/tFQw0yBlJLaFM93PS/8hmKnIlcUd3nPf/xxjXELViQMS2V4XMy4wKiNhr4+o4jpzJ1IhBo9od+a2W6GHanfWCuiYYIegLBb6htK8zbDU0ujai9Q/9PcmogYHkCxzkiYokPROnte4Qs6aTGo=
