language: node_js
node_js:
- '6'
branches:
  only:
  - master
before_install:
- npm install -g bower
- npm install -g brunch
install:
- npm install
script:
- brunch build --production
after_success:
- cd "$TRAVIS_BUILD_DIR"
- cd public
- git init
- git config user.name "travis"
- git config user.email "travis"
- git add .
- git commit -m "Travis build nr. $TRAVIS_BUILD_NUMBER"
- git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:gh-pages
  > /dev/null
- echo 'deployed!'
env:
  global:
  - secure: nV9yQp3FPzUhwFyple/O1eCTQvdrMPPODDKjsEnruUCekxcxwSLgzghQ6CmjrMRKeiMrdNamxs8i3CNFaOoGNOpKGNqBI7C68mhLb3jT82Q70f5rgQUjT+CXvAUe3PqlOgmcUhII1s3PCuqXEVic+55I2INRjo4RdWThJedjuvHUlvv29I+ICXh64sPRCJwRJbZO42XjNl1nknsqckQlR4dKkIpQb7KLsL/85jkv6793Q98LoLFJ5VbpIC3VuBPrnMRNyiVeabo4iKVoqZa70OJb5rKZWQFWar/DWDRhEgfoDKI/APQafoJNB09yEGYL28Xusv94svQnEOGC7R/e3RAwWAJXkEYKUVnsnHwdjwP3AbDUSFw0N965G05aU39l7nGmH6Yw2jeLyk0QCLPmbhB9sstJtJK/6fQrt2QOmd2gUioB0+LafxukNhwZBdLmcOrIJ0LmnWmBRvQhwmQxYYO/K6V7GchbasfLtZd+dBSXnRpf52QNKEPb+UC/FTJMTb7E1QypHqkvM30DnkRxJ/kCfrAJP0TZ/IV78hWLXrPUL2ySMuaQf4+RMCKfSoumPwwBEZHPv91y6lhW8TCkvOlUYXfkb3/811VdEuJT0VNxT81ZJew4kmfYBGJONelDD4jqLqoz0K7DJ2gHIkRzBRM3aYgoOIZNhmna1tKTjRU=
